### ISSUE TITLE
WebSocket on 2.0.4 Nuget

### ISSUE THREAD

**Issue by bryan-t** [damianh/ProxyKit#101]
Hi,

I've included ProxyKit 2.0.4 via Nuget. However, I think proxying of WebSockets are not yet included. Do I need to build it from source?

**Comment by damianh** [comment]
Correct, it is not included. It will be in the upcoming 2.1.0 release.

**Comment by bryan-t** [comment]
Do you have a tentative release date?

**Comment by damianh** [comment]
2.1.0-beta.1 is on nuget: https://www.nuget.org/packages/ProxyKit/2.1.0-beta.1

Thanks for your patience. I'm going to close this, but please report back if you have any issues, or indeed, it is working as desired.

Cheers.

**Comment by bryan-t** [comment]
Thank you so much!
