### ISSUE TITLE
Modify HttpClient's Message Handler from within the context of RunProxy Possible?

### ISSUE THREAD

**Issue by mrking** [damianh/ProxyKit#105]
I need to attach credentials to the HttpClientHandler if and only if the previous response from the server came back as 401 with an NTLM challenge. This due to a limitation with NetworkCredentials being attached where one is not being expected resulting an in [error with .net core](https://github.com/dotnet/corefx/issues/37672). 

I don't seen an obvious way to accomplish this when using httpClientBuilder.ConfigurePrimaryHttpMessageHandler. Is there any way to update the httpclient's message handler?

**Comment by damianh** [comment]
This is an interesting use case - authentication offloading to an NTLM secured upstream host. However ProxyKit fully relies on {HttpClientFactory](https://devblogs.microsoft.com/aspnet/asp-net-core-2-1-preview1-introducing-httpclient-factory/) to manage message handler lifecycles. Given the potential issues associated with managing HttpClient lifetimes I am not comfortable developing and support an alternative mechanism in ProxyKit. Also attaching credentials to the specific handler will result in side-effects / race conditions as handlers are reused for subsequent (and parallel) requests. The handler pipeline is also rebuilt on a timer (iirc).

Closing as there as I don't think there is anything I can do here unfortunately (it would be a nice feature). This feels like it needs to be reported to the HttpClientFactory team too. 

Kindly report back if you arrive at a solution.
