### ISSUE TITLE
Requests append / to the end of path

### ISSUE THREAD

**Issue by macsux** [damianh/ProxyKit#106]
Upstream requests seems to append / to the end of the request. Using http://mysite.com/get actually ends up being sent as http://mysite.com/get/

**Comment by damianh** [comment]
Can you paste your proxy configration from your startup.cs here please? Note, [nginx](https://docs.nginx.com/nginx/admin-guide/web-server/reverse-proxy/) uses trailing "/" for paths when configuring upstream hosts.

**Comment by damianh** [comment]
I think I've reproduced the issue. Well, at least found an inconsistency with nginx.

Given this `nginx.conf`

```
worker_processes auto;

events {
    worker_connections  1024;
}

http {
    include       mime.types;
    default_type  application/octet-stream;

    sendfile        on;

    keepalive_timeout  65;

    server {
        listen       5000;
        server_name  localhost;

        location / {
            proxy_pass   http://10.0.75.1:5002/bar;
        }
    }
}
```
The upstream server sees `/barget`

![image](https://user-images.githubusercontent.com/57436/59556995-98235c80-8fce-11e9-9bea-0fce99e643d7.png)

Given this proxykit config:

```csharp
public void Configure(IApplicationBuilder app)
{
    app.RunProxy(context => context
        .ForwardTo("http://10.0.75.1:5002/bar")
        .Execute());
}
```

The upstream server seed `/bar/get`.

![image](https://user-images.githubusercontent.com/57436/59557012-dc166180-8fce-11e9-86c8-85370bd6acd1.png)

**Comment by damianh** [comment]
While I have detected an inconsistency with nginx when regarding prepending a slash (I'll create another issue for that), I have not been able to reproduce your issue and so am closing.

If you believe the issue exists, kindle open a PR modifying one of the runnable samples that clearly shows the issue. Thank you.
