### ISSUE TITLE
Cannot use UsePathBase() in WebSockets/SignalR site

### ISSUE THREAD

**Issue by ChrisTorng** [damianh/ProxyKit#111]
I've tried 2.1.0-beta.1, found it doesn't support `UsePathBase()` in the WebSockets/SignalR site.

I use code from [17_SignalROnPath.cs](https://github.com/damianh/ProxyKit/blob/master/src/Recipes/17_SignalROnPath.cs), it shows `signalrApp.UseWebSocketProxy(context => new Uri("ws://upstream-host:80"));`. First, I suggest to use `ws://localhost:80` as sample target, because the next `RunProxy` uses `http://localhost:80`.

My target SignalR site uses `UsePathBase("/basepath")`. The problem happens when using `UseWebSocketProxy(context => new Uri("ws://localhost:80/basepath/"))`. The log shows:

    ProxyKit.WebSocketProxyMiddleware	Forwarding websocket connection to ws://localhost:80/path?id=...
    ProxyKit.WebSocketProxyMiddleware	Error connecting to server	
    Void MoveNext() System.Net.WebSockets.WebSocketException Unable to connect to the remote server
    System.Net.WebSockets.WebSocketException (0x80004005): Unable to connect to the remote server
       at System.Net.WebSockets.WebSocketHandle.ConnectAsyncCore(Uri uri, CancellationToken cancellationToken, ClientWebSocketOptions options)
       at System.Net.WebSockets.ClientWebSocket.ConnectAsyncCore(Uri uri, CancellationToken cancellationToken)
       at ProxyKit.WebSocketProxyMiddleware.AcceptProxyWebSocketRequest(HttpContext context, Uri upstreamUri) in /home/travis/build/damianh/ProxyKit/src/ProxyKit/WebSocketProxyMiddleware.cs:line 122

The wrong `ws://localhost:80/path?id=...` should be `ws://localhost:80/subpath/path?id=...`. According to [WebSocketProxyMiddleware.cs line 80](https://github.com/damianh/ProxyKit/blob/master/src/ProxyKit/WebSocketProxyMiddleware.cs#L80), the `relativePath` value is `/path`. Line 82-84 `var uriWithPath = new Uri(upstreamUri.Uri, relativePath.Length >= 0 ? relativePath : "");` will generate `ws://localhost:80/path`, that is wrong. The correct one is `ws://localhost:80/subpath/path`.

I use [Try .NET](https://try.dot.net/) with the following code:

    using System;
    public class Program
    {
      public static void Main()
      {
        Console.WriteLine(GetPath("ws://localhost:80/subpath/", "/path"));
        Console.WriteLine(GetPath("ws://localhost:80/subpath/", "path"));
        Console.WriteLine(GetPath("ws://localhost:80/subpath", "/path"));
        Console.WriteLine(GetPath("ws://localhost:80/subpath", "path"));
       }
      private static Uri GetPath(string upstreamUrl, string relativePath)
      {
        return new Uri(new Uri(upstreamUrl), relativePath.Length >= 0 ? relativePath : "");
      }
    }

The output is:

    ws://localhost/path
    ws://localhost/subpath/path
    ws://localhost/path
    ws://localhost/path

Only the second one is correct. According to [Uri Constructor: Uri(Uri, String)](https://docs.microsoft.com/en-us/dotnet/api/system.uri.-ctor?view=netcore-2.2#System_Uri__ctor_System_Uri_System_String_), its Remarks says: Additionally, if the `relativeUri` begins with a slash, then it will replace any relative part of the `baseUri`.

That means in the constructor of `Uri`, the `baseUri` should include the last back slash, and the `relativeUri` shouldn't includes back slash at the beginning. But for current code of `WebSocketProxyMiddleware.cs` line 80, the `relativePath` is always starts with back slash. That means I will never get `ws://localhost/subpath/path`, and have no way to use `/subpath` in WebSockets/SignalR site.

**Comment by damianh** [comment]
Thank you for the detailed bug report.

**Comment by damianh** [comment]
> First, I suggest to use ws://localhost:80 as sample target, because the next RunProxy uses http://localhost:80.

Fixed in https://github.com/damianh/ProxyKit/commit/674c18dc4c76517b5701f80f6e3d9ae4ea854b8e

**Comment by damianh** [comment]
I've been trying to reproduce your issue and I _think_ you have configuration problem, specifically around this: 

> The problem happens when using UseWebSocketProxy(context => new Uri("ws://localhost:80/basepath/"))

If I understand your scenario right, you have the outside url being `http://host:80/subpath/` that you want to forward to an upstream host `http://upstreamhost:80`? And the upstream host needs to know about the `/subpath/` so it can generate URLs correctly etc.? (Personally I prefer to use [X-Fowarded-PathBase](https://github.com/damianh/ProxyKit#23-x-forwarded-headers) so it can be determined at runtime be changeable vs baking it in code/config).

If this is correct, then puthing the path on in the URI to forward to is not correct. Instead you should use `.Map()` to forward requests from `/subpath/` to your upstream host. 

Such a configuration will look like:

```csharp
app.Map("/subpath", appInner =>
{
    app.UseWebSocketProxy(context => new Uri("ws://localhost:5001"));
    app.RunProxy(context => context
        .ForwardTo("http://localhost:5001")
        .AddXForwardedHeaders()
        .Send());
});
```

I've added a sample runnable SignalR project to the ProxyKit solution where you can try this out:

**Comment by ChrisTorng** [comment]
First, thanks for all your work on ProxyKit and all the time spending on my issue.

I must admit that I don't really understand ProxyKit/WebSocket/SignalR/UsePathBase/X-Forwarded-* well enough. And a good issue report is not easy. Even git/github/PR is not familiar to me.

My outside url is `http://host:80/subpath`, the upstream host is running under `http://upstreamhost:80/subpath`. I wish they are using the same subpath, to avoid more url inconsistant problem.

I was thinking `UsePathBase()` is the key to use `subpath` in upstream host, but it seems to be wrong. My project is currently using `launchSettings.json`'s `iisExpress`-`applicationUrl` to set to `http://localhost:80/subpath` and using IIS Express. (IIS Express can't use port 80 as I know, here is just an example) I'm still trying to reproduce the same situation in the `SignalRSimpleChat` project, but changing `.UseUrls("http://localhost:5001")` to `.UseUrls("http://localhost:5001/subpath")` generate error:  A path base can only be configured using IApplicationBuilder.UsePathBase(). So I'm still struggling for how to reproduce my issue. I need more time to understand how they all been constructed.

Maybe I need to remove the `/subpath` from upstream host, to follow the standard way behind reverse proxy. But I still think that current ProxyKit's code can't construct a url like `ws://localhost:80/subpath/path` just like what had been mentioned in my report.

**Comment by damianh** [comment]
Fixed via your PR repro and https://github.com/damianh/ProxyKit/commit/732cecdb94645364df5f5aa5492e2f1aedc103d8
