### ISSUE TITLE
Avoid GetRequiredService in ForwardTo?

### ISSUE THREAD

**Issue by abergs** [damianh/ProxyKit#124]
Treat this issue as an invitation to a discussion rather than a bug.

I'm analyzing the memory usage with dotMemory when running 125 concurrent connections "bombarding" the proxy over 7 min. Total request count around 138k.

The memory pattern is quite bumpy:
![image](https://user-images.githubusercontent.com/357283/59607693-19383c00-9114-11e9-9995-000f58ae57b0.png)

I'm seeing this:
![image](https://user-images.githubusercontent.com/357283/59607506-c068a380-9113-11e9-8037-14f05804b719.png)

Which expands to this:
![image](https://user-images.githubusercontent.com/357283/59607572-dc6c4500-9113-11e9-9275-b84d4ebfd093.png)

I'm thinking the call to GetRequiredService is triggering reflection?

**Comment by abergs** [comment]
I cloned the repo and made a ugly test by adding ProxyKitClient as a optional argument in the Forwardto-method.
![image](https://user-images.githubusercontent.com/357283/59610126-05db9f80-9119-11e9-8009-c9f00c976371.png)

I instead initialized it once in startup and re-use that instance.

This removed the Finalized objects observed earlier.
Still seeing bumpy memory allocations though.

**Comment by damianh** [comment]
Awesome report!

Can you share your test project on github? I feel the total request count is a bit on the low side 🤔 . I'd like to locally reproduce what you are seeing.

Thanks!

**Comment by abergs** [comment]
@damianh Do you mean the fork of ProxyKitClient or "my application" using it? The application is unfortunately not something I can open source... but it's a small .net core app that maps a route, does some header parsing and then forwardsTo.

**Comment by damianh** [comment]
Post the fork changes to a branch on your repo for a start. I don't need your application but maybe some indication of what it does so I can put the total requests into some context. If you can, please share your proxy config (header parsing etc), what tool you are using to generate the load and maybe some indication of the system it is being run on.

Would like to get to as like-for-like as possible.

**Comment by abergs** [comment]
I used https://github.com/codesenberg/bombardier to generate the load and fetched a HTML url that weighs around 10kb with 125 concurrent connections for 7m.

Before i run proxykit i just read a string value from the headers with a date, like "deployment-190624-1111".

It ran on my laptop (with other apps running) so the benchmark should **not** be treated like a sure thing and would probably vary a lot depending on profiling.
However, the reflection caused a lot of queued Finalization so the optimization is probably a good thing. The "GetRequiredService" should probably not be done by the client but somewhere "up the chain" in ProxyKit (not in the hotpath) or cached in a sane manner. 

Spec:
Win 10 Enterprise latop
CPU: i7 7820 @ 2,90 GHz 4 cores, 8 logical.
16GB ram.

**Comment by damianh** [comment]
v2.2.1 is on nuget.org with this specific issue addressed. I'll do further profiling in a subsequent release.

**Comment by saithis** [comment]
@damianh Doesn't this now only instantiate HttpClient once and always use this single intance? If I remember correctly, then this has the sideeffect, that DNS ttl is ignored. 

Last time I checked, the HttpClientFactory switched the HttpClientHandler (which resolves each DNS only once) for new HttpClients every few minutes so that the DNS ttl is respected, but that doesn't work if the HttpClient is kept as a singleton.

**Comment by damianh** [comment]
Hmm, thought it rebuilt the handlers internally..
 Will check asap and revert if so.

**Comment by damianh** [comment]
I've unlisted the 2.1.1 package pending investigation.

**Comment by damianh** [comment]
Yes, it seems that HttpClient (via `ProxyKitClient`) needs to be considered transient and activated and retrieved on per-request basis. I've reverted #125 and related changes. 

I'll profile things to see what can be done wrt allocations.

**Comment by saithis** [comment]
Maybe you can inject the IHttpClientFactory (which is a singleton) and call CreateClient() when needed to get the HttpClient. If that doesn't solve the allocation problem, then you could probably cache the created HttpClient for a short duration. A setting for the duration would then be useful with duration 0/null equals no caching.

**Comment by damianh** [comment]
That is what I am currently thinking except it means I can't use a typed client. (May or may not be an issue).

Am gonna profile before first so I have some local data to work with

**Comment by damianh** [comment]
Did a mini profile and the difference between resolving a typed client and named client is surprisingly large: 

![image](https://user-images.githubusercontent.com/57436/61116779-6a2e1c80-a495-11e9-9e60-befee68222aa.png)

Thus I don't think it's `GetRequiredService<>` per se, but activation of the typed client.

I'm going to move to using named client.

**Comment by damianh** [comment]
It's _not_ a cache warm up issue either

![image](https://user-images.githubusercontent.com/57436/61117665-4f5ca780-a497-11e9-8eee-e5ea2346a272.png)

**Comment by damianh** [comment]
Regarding the rest of the bumpy memory usage, I suspect it's heavily related to allocation regarding HttpClient usage. I don't know how much I can optimize there from the outside (i.e. object pooling) but will dig in separately.

**Comment by damianh** [comment]
@abergs 2.1.2 on nuget.org. Thanks again for the report.

**Comment by damianh** [comment]
Further validation that the problem appears to be in `HttpClientFactory`
 - https://twitter.com/thoemmi/status/1149655040686055425
 - https://twitter.com/davidfowl/status/1149648815147741184

**Comment by rynowak** [comment]
Thanks for the report, I'm following up on this.

**Comment by abergs** [comment]
Fixed here: https://github.com/aspnet/Extensions/pull/2063
