### ISSUE TITLE
Proxing to a specific file (SPA)

### ISSUE THREAD

**Issue by Enngage** [damianh/ProxyKit#130]
Hi!

I'm trying to forward requests on specific path to an Azure blob storage container where entire SPA (Angular) app is hosted. 

I'm using this code which works perfectly fine:

```
      app.UseWhen(
                context => context.Request.Path.Value.StartsWith("/my-angular-app"),
                appInner => appInner.RunProxy(context =>
                {
                    context.Request.Path = "/index.html";
                    return context
                        .ForwardTo("http://mystorage.blob.core.windows.net/container")
                        .AddXForwardedHeaders()
                        .Send();
                }));
```

However, it doesn't feel right overwriting the `context.Request.Path`. Is there a better of accomplishing this? Maybe there could be an option to specify target file?

**Comment by damianh** [comment]
What you are doing is request path rewriting and it looks totally fine to me. **All** requests that start with `/my-angular-app`, i.e `/my-angular-app/foo?a=b` you will want to load your SPA app and have your angular router handle the rest of the path & query. That is what you are doing here.

Another way I've seen this be done is a catch-all MVC route `[HttpGet("{*uri}")]` (or something like that) where the handler, returns a local file static file, renders a vew, or does a HTTP request to load the static content from CDN (basically the same as what you are doing here).

Actually, I'll think I'll add this as a recipe. 

Cheers.

**Comment by damianh** [comment]
> Maybe there could be an option to specify target file?

Btw, if I add that as a feature, it would only be doing what you have here, under the hood. I like the explicitness shown here - I think this is the best way to accomplish this.

**Comment by Enngage** [comment]
Thanks for getting back to me @damianh :) 

It would be great to have an extension method for this purpose as this is sort of hidden, and not really obvious at first glance. I've had to inspect to source code to see whats going on. 

Anyway it works really good thus far and seems like I'll keep using it this way.
