### ISSUE TITLE
Make a HTTPS Forward Proxy

### ISSUE THREAD

**Issue by clintnetwork** [damianh/ProxyKit#138]
Hi,

I would like to make a dynamic forward HTTPS proxy with authentication, do you think that its possible and do you have a snippet ?

Thank you !

**Comment by clintnetwork** [comment]
Ha I found this https://github.com/damianh/ProxyKit/blob/master/src/Recipes/03_TenantRouting.cs 😜

**Comment by clintnetwork** [comment]
So last question ^^

Do you think if its possible to use `ProxyKit` to forward flow to other HTTPS proxies ?

How i do this ? only configuring an upstream in http like http://192.168.0.25 ?

**Comment by damianh** [comment]
Hi @clintnetwork,this project is focused on reverse proxies only (perhaps I should have called it _Reverse_ProxyKit...). Althogh I would like to see a such a project, I don't have any intention to develop a forward proxy here.

**Comment by clintnetwork** [comment]
Hey,

I understand, I just had some questions about how to get and parse the incoming stream, I tried and I don't win :/
