### ISSUE TITLE
How to set UseDefaultCredentials for the HttpClient

### ISSUE THREAD

**Issue by andrewjboyd** [damianh/ProxyKit#167]
How could I set UseDefaultCredentials for the HttpClient?

**Comment by andrewjboyd** [comment]
So I simply created a handler
`       HttpMessageHandler CreateHttpPrimaryHandler()
        {
            return new HttpClientHandler
            {
                AllowAutoRedirect = false,
                UseDefaultCredentials = true,
                UseCookies = false
            };
        }`

and then I passed it in
`services.AddProxy(httpClientBuilder => httpClientBuilder.ConfigurePrimaryHttpMessageHandler(CreateHttpPrimaryHandler));`

**Comment by damianh** [comment]
That's exactly how to do it.
