### ISSUE TITLE
Method body removing while forwarding GET,HEAD,DELETE requests

### ISSUE THREAD

**Issue by osoykan** [damianh/ProxyKit#168]
Hi,

One of our teams needed to keep the method body during the forwarding of the request. Which points us to  
https://github.com/damianh/ProxyKit/blob/775348040e4d6b0ba9c18e8b47ae1bdf603bb04e/src/ProxyKit/HttpContextExtensions.cs#L44-L52
statements that remove the method body. 

Some StackOverflow answers also say that it is not strictly forbidden.
https://stackoverflow.com/questions/299628/is-an-entity-body-allowed-for-an-http-delete-request/299696#299696 
So, the server might redirect the request body to downstream but, handling and ignoring is up to downstream application/server in this case.

Can we change this behavior or some selector Func for which keywords can be ignored?
Any thoughts appreciated.

**Comment by damianh** [comment]
This is copy-pasta from the the original MS AspNet proxy (attempt). I saw it and thought "I'll wait until someone has a problem with this" :)

I know elastic search APIs leverage GET's with a body. I think I'll just remove this, pass through whatever and the let the upstream host handle whether it thinks it's an issue or not.

**Comment by osoykan** [comment]
That's great!, I'm glad there is no reasoning behind that we need to tackle :)

Looking forward to getting the changes.
Thanks @damianh
