### ISSUE TITLE
Response.Content.Headers are not the same as original ones

### ISSUE THREAD

**Issue by orzelek12** [damianh/ProxyKit#171]
I noticed that when I'm trying to rewrite the OPTIONS request the way it is to the other server,
I got response with different headers than I would get when calling other server directly.

I used simple echo json site to test it out http://echo.jsontest.com/key1/val1/key2/val2
See in the image posted bellow, that Allow header is different that in original call (yellow highlight).
It is being located in HttpResponseMessage.Content.Headers.
I double checked and the HttpResponseMessage I return from my lambda exp inside app.RunProxy() contains correct headers (response.Content.Headers are exact the same as the ones I get in Postman during direct call).

Is there some piece of code that changes the Allow header in Response Content after RunProxy delegate is done? Is there a reason for that?

I also noticed that two extra headers were added to the response (green highlight). Is there a way to get rid of them? I'm not using .AddXForwardedHeaders()

![image](https://user-images.githubusercontent.com/17751350/66841235-aa57dc00-ef69-11e9-8894-6af1a14103e8.png)

**Comment by vmateiaiv** [comment]
I have exactly the same problem for a DELETE request. The body is not forwarded. 
private static HttpRequestMessage CreateProxyHttpRequest(this HttpRequest request)
        {
            var requestMessage = new HttpRequestMessage();
            var requestMethod = request.Method;
            if (!HttpMethods.IsGet(requestMethod) &&
                !HttpMethods.IsHead(requestMethod) &&
                **!HttpMethods.IsDelete(requestMethod) &&**
                !HttpMethods.IsTrace(requestMethod))
            {
                var streamContent = new StreamContent(request.Body);
                requestMessage.Content = streamContent;
            }
.....
}

**Comment by osoykan** [comment]
@vmateiaiv This behavior has been changed with https://github.com/damianh/ProxyKit/pull/173. Which version are you using?

**Comment by vmateiaiv** [comment]
@osoykan you just made my day! Thanks a lot!

**Comment by damianh** [comment]
@orzelek12 

> two extra headers were added to the response (green highlight). Is there a way to get rid of them?

They are coming from aspnet core (mvc), not ProxyKit. I refer you to AspNetCore docs regarding.

> Is there some piece of code that changes the Allow header in Response Content after RunProxy delegate is done? 

No. You can see for yourself: https://github.com/damianh/ProxyKit/blob/master/src/ProxyKit/ProxyMiddleware.cs#L30-L62  There is only one header removed `transfer-encoding` everything else is untouched, _in ProxyKit_. There can of course be other middleware in your AspNetCore pipeline performs changes as well as your custom code as well as your host (lambda). I don't have access to your code to see, so I can't help any further.
