### ISSUE TITLE
Why was RunProxy(path, delegate) made obsolete?

### ISSUE THREAD

**Issue by abergs** [damianh/ProxyKit#185]
The change I'm referring to is this:
https://github.com/damianh/ProxyKit/commit/c09519887d2fdca65c5fecd3e270e1870331e960

We're using it quite actively and I'd just like to understand if there was any underlying issues or it was to keep the API slim.

**Comment by damianh** [comment]
Hi @abergs,

As you can see from that commit it was just an extension method that called `.Map()` followed by `UseMiddleware()`. Yes I desire to keep the API slim. I wasn't happy about basically hiding a well documented AspNetCore method with an unfamiliar one that didn't really provide any value and (arguably) made things less explicit. Users may want do other bits of work in the mapped path application builder delegete [just above this line](https://github.com/damianh/ProxyKit/blob/master/src/Recipes/02_Paths.cs#L20) before ProxyKit is invoked.

If you want to keep your code intact, it would be easy to add the extension method to your own code.

**Comment by abergs** [comment]
Thank you for taking the time to elaborate. I support your decision.
    	
    	

    	Get Outlook for iOS
    
  




On Sat, Nov 16, 2019 at 9:26 PM +0100, "Damian Hickey" <notifications@github.com> wrote:












Hi @abergs,


As you can see from that commit it was just an extension method that called .Map() followed by UseMiddleware(). Yes I desire to keep the API slim. I wasn't happy about basically hiding a well documented AspNetCore method with an unfamiliar one that didn't really provide any value and (arguably) made things less explicit. Users may want do other bits of work in the mapped path application builder delegete just above this line before ProxyKit is invoked.


If you want to keep your code intact, it would be easy to add the extension method to your own code.

**Comment by damianh** [comment]
Thank you.
