### ISSUE TITLE
No service for type 'System.Net.Http.IHttpClientFactory' has been registered error message

### ISSUE THREAD

**Issue by aviorn** [damianh/ProxyKit#193]
Hi 
I am using proxykit 2.2 in a dotnet core 2.2 web application 

I am using my  middleware to catch the requests and when the path is right i forward it to proxy

and getting an error message 
No service for type 'System.Net.Http.IHttpClientFactory' has been registered
in this line :                             
var forwardContext = ctx.ForwardTo(item.TargetUri); 

here is the code 

    app.UseWhen(
                        context => context.Request.Path.StartsWithSegments(new PathString(item.SourcePrefix)),
                        appInner => appInner.RunProxy(ctx =>
                        {                           
                            var forwardContext = ctx.ForwardTo(item.TargetUri); 
    ); 
                            string token = forwardContext.HttpContext.CreateJwtFromContext(item.JwtIssuer, item.JwtKey); 
                            forwardContext.UpstreamRequest.Headers.Authorization = new System.Net.Http.Headers.AuthenticationHeaderValue("Bearer", token);

                            return forwardContext.Send();
                        })

                    );

i have tried to provide httpClient according to this documentation  
https://github.com/damianh/ProxyKit#24-configuring-proxykits-httpclient
but does not work  and i get an error

**Comment by damianh** [comment]
Are you doing `services.AddProxy()` as per https://github.com/damianh/ProxyKit/blob/master/README.md#12-forward-http-requests ?

**Comment by damianh** [comment]
This happens when you forget to call service.AddProxy(). I've added a nicer error message when this happens.
