### ISSUE TITLE
Proxy SignalR and appending access tokens

### ISSUE THREAD

**Issue by hoaol** [damianh/ProxyKit#201]
Hi! I'm using ProxyKit for building a BFF for a React SPA application. We are using Oath2/OIDC for protecting our API calls. My first attempt to use ProxyKit was just proxying the requests like in your samples and we added the Bearer token on the front end. This worked without problem. On the client we are using @aspnet/signalr as their signalR client and we supplied the token like this
```
 this._connection = new signalR.HubConnectionBuilder()
            .withUrl(CASE_SIGNALR_URL, {
                accessTokenFactory: () => localStorage.getItem("My Access Token")
            })
            //.configureLogging(signalR.LogLevel.Error)
            .configureLogging(signalR.LogLevel.Information) // Change to LogLevel.Error before final deployment
            .build();
```
One purpose of using the BFF is to handle the token there instead of in the client so we removed the 
`accessTokenFactory`
part:
```
 this._connection = new signalR.HubConnectionBuilder()
            .withUrl(
                CASE_SIGNALR_URL
            )
            //.configureLogging(signalR.LogLevel.Error)
            .configureLogging(signalR.LogLevel.Information) // Change to LogLevel.Error before final deployment
            .build(); 
```
In my startup class I have this code:

```
            app.Map("/signalR", signalR =>
            {
                signalR.UseWebSocketProxy(
                    context => new Uri(_appSettings.ApiGatewayRootUrlWs));
                signalR.RunProxy(async context =>
                {
                    var forwardContext = context.ForwardTo(new Uri(_appSettings.ApiGatewayRootUrlHttp));
                    var token = await context.GetTokenAsync("access_token");
                    if (token == null)
                    {
                        _logger.LogError("No token available for the SignalR related request with Path: " + context.Request.Path);
                    }
                    forwardContext.UpstreamRequest.Headers.Add("Authorization", "Bearer " + token);
                    forwardContext.AddXForwardedHeaders();
                    return await forwardContext.Send();
                });
            });
```
It seems that we get an error when trying to negotiate the connection, the SignalR service returns a 500 insted of 101 
```
System.Net.WebSockets.WebSocketException (0x80004005): The server returned status code '500' when status code '101' was expected.
   at System.Net.WebSockets.WebSocketHandle.ConnectAsyncCore(Uri uri, CancellationToken cancellationToken, ClientWebSocketOptions options)
   at System.Net.WebSockets.ClientWebSocket.ConnectAsyncCore(Uri uri, CancellationToken cancellationToken)
   at ProxyKit.WebSocketProxyMiddleware.AcceptProxyWebSocketRequest(HttpContext context, Uri upstreamUri)
```
I understand that this may not be  enough information to help with my trouble shooting but maybe you can give my feedback if I'm doing something obviusly wrong

Best regards Hans

**Comment by damianh** [comment]
Hi @hoaol , reading through the snippets there isn't anything jumping out to me as to what the issue could be. To be honest, there could be any number of things going on - I'm going to need a I need a runnable project that reproduces the issue. There is a signalr chat app in the repo, perhaps adjust that to match your setup.

**Comment by hoaol** [comment]
Hi! I just wanted to mention that I solved this. 

I think it was more related to how we have implemented the security in our SignalR Services (or maybe not, I have not implemented that part my self). 
In addition to attaching the Bearear Token for the http related request to the SignalR Service I also needed to add it to the wss query string, My code ended up like this: 

```
app.Map("/signalR", signalR =>
{
	signalR.UseWebSocketProxy(
		context =>
		{
			var token = Task.Run(async () => await context.GetTokenAsync("access_token")).Result;
			context.Request.QueryString = new QueryString(context.Request.QueryString + "&access_token=" + token);
			return new Uri(_appSettings.ApiGatewayRootUrlWs);
		}
	);
	signalR.RunProxy(async context =>
	{
		var forwardContext = context.ForwardTo(new Uri(_appSettings.ApiGatewayRootUrlHttp));
		var token = await context.GetTokenAsync("access_token");
		forwardContext.UpstreamRequest.Headers.Add("Authorization", "Bearer " + token);
		forwardContext.AddXForwardedHeaders();
		return await forwardContext.Send();
	});
});
```
Thanks for you quick feedback and a great proxy toolkit :-)

Best regard Hans

**Comment by damianh** [comment]
Good to hear you solved it!

Cheers.
