### ISSUE TITLE
How to log errors?

### ISSUE THREAD

**Issue by drauch** [damianh/ProxyKit#244]
Note: we cannot switch to Microsoft's proxy server yet, as it does not support our in-depth self-baked client certificate validation yet. Therefore we're "stuck" with ProxyKit, which does its job well :-)

Two open logging questions though:

* How to log request errors? We want to log a reason when a request failed, e.g., timeout or server not reachable, etc. how to integrate into the pipeline so that we can do that?
* How to log if a client tries to connect without a client certificate?

**Comment by damianh** [comment]
Hi @drauch ,

ProxyKit is no longer being maintained, sorry not going to spend any time on this. If you need to continue using it, you'll need to fork it.
