### ISSUE TITLE
Migrate to YARP - step by step

### ISSUE THREAD

**Issue by 304NotModified** [damianh/ProxyKit#245]
It would be great if there would be step by step migration plan. :)

**Comment by damianh** [comment]
Hi @304NotModified 

Sorry not going in invest time in this. If someone wants to do a blog post or similar I'd be happy to link to it.

As a ProxyKit user, this sample code should be obvious enough: 

https://github.com/microsoft/reverse-proxy/blob/main/samples/ReverseProxy.Direct.Sample/Startup.cs#L36-L63
