### ISSUE TITLE
HTTP to HTTPS Redirect

### ISSUE THREAD

**Issue by lwalker-kforce** [damianh/ProxyKit#28]
I have a simple redirect configured where the upstream host URL is https. The proxy's endpoint is http. During inspection (using webhook.site, the x-forwarded-proto and x-original-proto are both http. I am making an assumption the x-forwarded-proto should be https if my target/destination (right side of the proxy) was configured with an https protocol. Can someone elaborate or provide clarity on how I can configure to ultimately do an http-https forward?

**Comment by damianh** [comment]
According to https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Forwarded-Proto

> The `X-Forwarded-Proto` (XFP) header is a de-facto standard header for identifying the protocol (HTTP or HTTPS) that a client used to connect to your proxy or load balancer.

And you say:

> The proxy's endpoint is http. 

If the proxy endpoint is HTTP then that is what `X-Forwarded-Proto` header will be.

Closing as it sounds like things are working as expected.

**Comment by lwalker-kforce** [comment]
Thank you for the response. I would like to reopen this issue though please. I failed to communicate this issue fully. 

Removing the headers for a moment, I have configured my upstream host with an **HTTPS** protocol. My reverse proxy endpoint is **HTTP**. My expectations was/is that the incoming request to the reverse proxy (HTTP) would be forwarded to to the configured upstream host (HTTPS). Based on what I am seeing, it is not. I have attached my Startup.cs (as txt) as well as a pic of webhook.site, which I am using for testing. In the pic, you can see in the Request Details section that the POST to webhook.site was to an HTTP URL. 

![image](https://user-images.githubusercontent.com/4869444/51410223-f63c3880-1b31-11e9-91a4-06d19090f30f.png)

[Startup.txt](https://github.com/damianh/ProxyKit/files/2774338/Startup.txt)

**Comment by damianh** [comment]
Yes I can see what you mean now from the screens.

I tried this with the site with just a bog standard HTTP call:

![image](https://user-images.githubusercontent.com/57436/51417896-9620b300-1b80-11e9-89e1-3e9a8aa8d8fb.png)

... and it still showed `http` in webhook.site:

![image](https://user-images.githubusercontent.com/57436/51417911-b9e3f900-1b80-11e9-9262-b781259921e4.png)

Then I tried using a browser:

![image](https://user-images.githubusercontent.com/57436/51418168-33c8b200-1b82-11e9-9033-2a8645170b08.png)

And it still said `http`:

![image](https://user-images.githubusercontent.com/57436/51418179-4511be80-1b82-11e9-9128-65dc16856003.png)

This looks like an issue with `webhook.site` - it never shows `https`

**Comment by lwalker-kforce** [comment]
Thanks again for such a quick response. I just tested using [`Hookbin`](https://hookbin.com) and it looks like there may be an issue with `webhook.site`, as you mentioned. Below is the header showing the request was over port 443, as expected.

![image](https://user-images.githubusercontent.com/4869444/51418969-eb46cf80-1b54-11e9-8900-dc6758fd2984.png)

**Comment by damianh** [comment]
Ok that's good to hear :) Thanks for validating.

**Comment by gurramnag** [comment]
Hi Experts,

I am new to webhook. 

I have created a webhook URL, i.e 
**http://webhook.site/c2269d1e-f578-43ce-841a-88a516ced09f**

Later, I have implemented a REST webservice using spring boot which is working fine and getting list of data i.e,
**http://localhost:8786/api/newCoordinates** 

![api](https://user-images.githubusercontent.com/18136671/59027991-0dc55500-8878-11e9-8774-697e9d57ecba.png)



Now, I am trying like when I call webhook link **http://webhook.site/c2269d1e-f578-43ce-841a-88a516ced09f** it should has to redirect to above REST api  service **http://localhost:8786/api/newCoordinates**  and get the response data.But I didn't get any expected data.

To achieve this, I tried XHR Redirect setting like below,

![XHR_redirect_settings](https://user-images.githubusercontent.com/18136671/59028125-6399fd00-8878-11e9-89d3-c0e10a3074e3.png)


But it is not redirecting to my  http://localhost:8786/api/newCoordinates , please help me how can achieve it.

Thank you.

**Comment by damianh** [comment]
@gurramnag What has your question got to do with this project?
