### ISSUE TITLE
Drop incoming X-Forwarded headers by default & opt-in to forwarding them

### ISSUE THREAD

**Issue by damianh** [damianh/ProxyKit#30]
1. Currently ProxyKit will forward all incoming request headers to the upstream host, including `X-Forwarded-*`.
2. Chaining proxies is not unusual and the `X-Forwarded` [spec accomdates that](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Forwarded-For).
3. A developer can optionally apply proxy X-Forwarded headers to the upstream request using `ApplyXForwardedHeaders()`.

The current design is that the first reverse proxy in a chain will accept external `X-Forwarded-*` headers and forwarding them by default. In order to mitigate against potential spooking attacks, the headers should be dropped by default and accepting them is an explicit opt-in decision.

The API for this could look like:

```csharp
app.RunProxy(context => context
    .ForwardTo("http://localhost:5001")
    .ApplyXForwardedHeaders(append: true)
    .Execute());
```

1. If `X-Forwarded-*` headers don't exist on incoming request, `X-Forwarded-*` are **added**.
2. If `X-Forwarded-*` headers exist on incoming request and `append:false` (default), they are **replaced**.
3. If `X-Forwarded-*` headers exist on incoming request and `append:trye` (opt-in), they are **appended**.

Pinging @leastprivilege @brockallen for feedback :)

**Comment by brockallen** [comment]
Are there any other headers like that, where they're used to communicate internally between those hops?

**Comment by damianh** [comment]
There aren't any other headers (other that #11 in time). Thanks for feedback.

This made me laugh (from http://www.sec-down.com/wordpress/?p=809 )

![image](https://user-images.githubusercontent.com/57436/51484682-72d24f80-1d9c-11e9-9473-0515d8795e9d.png)

**Comment by damianh** [comment]
> then that's the one you need to provide this sort of control over

The total control is there but I guess it's probably better to protect people from themselves.
