### ISSUE TITLE
How to use HSTS with ProxyKit

### ISSUE THREAD

**Issue by doggy8088** [damianh/ProxyKit#35]
I tried `app.UseHsts();` with ProxyKit, but it doesn't working.  

```cs
app.UseHsts();
app.RunProxy(context => context.ForwardTo(url).Execute());
```

How can I use ProxyKit with HSTS middleware?

**Comment by damianh** [comment]
Works fine for me:

![image](https://user-images.githubusercontent.com/57436/51605649-eb0d5200-1f0f-11e9-8882-b0f737adac75.png)

And without:

![image](https://user-images.githubusercontent.com/57436/51605853-81417800-1f10-11e9-92a0-c3b4774a64d9.png)

**Comment by doggy8088** [comment]
@damianh I finally realized that the HSTS won't do redirection from HTTP to HTTPS.  I was tested on HTTP and expected browser to redirect to HTTPS. 😝

**Comment by damianh** [comment]
No, HSTS middleware doesn't do redirection. For that, use [`.UseHttpsRedirection()`](https://docs.microsoft.com/en-ie/dotnet/api/microsoft.aspnetcore.builder.httpspolicybuilderextensions.usehttpsredirection?view=aspnetcore-2.2).

The HSTS middleware only adds the header if the request is `HTTPS` and *not* on a loop back address too.

**Comment by damianh** [comment]
I don't, no. Writing your own custom middleware for this seems like the right approach.
