### ISSUE TITLE
X-Forwarded-Host missing Port

### ISSUE THREAD

**Issue by timscriv** [damianh/ProxyKit#43]
Currently trying to build a proxy to an application that needs to build a redirect url to the Proxy location rather than the forwarded location. This application will be forwarded to from a number of locations so it must be dynamic. By default .Net core will build this redirect with either the `Host` header that can be overriden with the the `X-Forwarded-Host` header, using the `app.UseXForwardedHeaders` automatically. 

My issue is that currently the `X-Forwarded-Host` header is missing the port (e.g. `localhost` rather than `localhost:5000`), this would probably not affect production scenarios as they will use the `80` port. 

Is this intentionally to remove the port in `XForwardedExtensions.cs` `Line 59` or can I submit a PR that will change that from `host.Host` to `host.Value` (which resolves the issue) 

Here are the resources I have found suggesting that `X-Forwarded-Host` should contain the host and port:
https://en.wikipedia.org/wiki/List_of_HTTP_header_fields#Common_non-standard_request_fields
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Forwarded-Host

**Comment by damianh** [comment]
I'm going to go with including the port every time. Thanks for the offer of a PR; am at the computer right now with the project open so I just went ahead.

**Comment by damianh** [comment]
@timscriv 2.0.3 on nuget.org. Let me know how it goes. Cheers.
