### ISSUE TITLE
RoundRobbin: Integer overflow with Interlocked.Increment

### ISSUE THREAD

**Issue by vcsjones** [damianh/ProxyKit#44]
Here:

https://github.com/damianh/ProxyKit/blob/ebc9ac5363122ded184d5f15277f96cbcb0af987/src/ProxyKit/RoundRobin.cs#L52

`_position` is incremented for each incoming request. After `int.MaxValue` (2 billion) requests, the `_position` will wrap around to -2,147,483,648 and break indexing into the distribution.

2 billion requests is a lot, but not improbable for months of uptime from a proxy. The easiest fix is to keep `_position` as a `long`. 2^63 requests is a _lot_ and probably more than the lifetime of the process. 

At 1,000,000 req/s, the signed 32-bit integer will overflow in about 35 minutes.
At 1,000,000 req/s, the signed 64-bit integer will overflow in about 292,471 years.

A "permanent" fix would be to reset the counter instead of using mod when reaching the end, but that can be tricky to do lockless and safely.

**Comment by damianh** [comment]
Damn and I just released 2.0.1 lol

**Comment by vcsjones** [comment]
Fixed in #45. Forgot to mark it to close this.
