### ISSUE TITLE
Set ClientCertificate for HttpClient

### ISSUE THREAD

**Issue by frocentus** [damianh/ProxyKit#70]
Hello, 
is there a way to pass an HttpClientHandler Object to the underlying HttpClient to add a ClientCertificate to the outgoing Request (ForwardContext)?
I tried to configure the HttpClient in the ConfigureServicesMethod, but I did not get it :)

tia

**Comment by frocentus** [comment]
A little bit too fast...
Am I correct, to set the clientcertificate via the ConfigurePrimaryHttpMessageHandler method? If yes, please close this issue as irrelevant :)

**Comment by damianh** [comment]
That is _almost_ how to do it. HttpClientFactory will dispose of your handler after a period of time and re-create them. Your code will work for about two minutes and then stop working with ObjectDisposeExceptions

Instead do this:

```csharp
var cert2 = new X509Certificate2();
Func<HttpMessageHandler> createPrimaryHandler = () =>
{
    var clientHandler = new HttpClientHandler();
    clientHandler.ClientCertificates.Add(cert2);
    clientHandler.ClientCertificateOptions = ClientCertificateOption.Manual;
}

services.AddProxy(httpClientBuilder => httpClientBuilder.ConfigurePrimaryHttpMessageHandler(createPrimaryHandler));
```

Do fancy sending a recipe as a PR? 😊
