### ISSUE TITLE
Ignore Invalid SSL certificate?

### ISSUE THREAD

**Issue by datvm** [damianh/ProxyKit#73]
I have a simple Proxy:

```
            app.RunProxy(context =>
            {
                var message = context
                    .ForwardTo("https://localhost:19101")
                    .Send();

                return message;
            });
```

Problem the SSL served at localhost:19101 is not valid (it is from Cloudflare). I have tried installing it to my Trusted Root CA but it still does not work.

The exception is:

> AuthenticationException: The remote certificate is invalid according to the validation procedure.
> System.Net.Security.SslState.StartSendAuthResetSignal(ProtocolToken message, AsyncProtocolRequest asyncRequest, ExceptionDispatchInfo exception)
> 
> HttpRequestException: The SSL connection could not be established, see inner exception.
> System.Net.Http.ConnectHelper.EstablishSslConnectionAsyncCore(Stream stream, SslClientAuthenticationOptions sslOptions, CancellationToken cancellationToken)

I understand why I receive it but is there any way to bypass it?

**Comment by datvm** [comment]
I have added an option for this. Sorry I didn't understand how Pull Request works, so I accidentally push it in my fork's master branch so now the other Pull Request includes this one too. This added option does require the previous fix though.

How to use:

```
            services.AddProxy(configureOptions: options =>
            {
                options.IgnoreSSLCertificate = true;
            });
```

Or

```
            services.AddProxy();
            services.Configure<ProxyOptions>(options => options.IgnoreSSLCertificate = true);
```

I do not understand your UnitTest yet, so please help me write a Test for it. I myself test with my own project already and it is working well.

Sorry again for the messed up.

**Comment by damianh** [comment]
I'm not sure about this - feels like we need a better way that doesn't enable a user to accidentally ship that to production (which would be really bad).

To do two separate PRs do the changes on two separate branches.

**Comment by datvm** [comment]
The default value is `false` so they can use `#if DEBUG` if they are intended for dev only. As for me, I need it for Production (the scenario I described above).

**Comment by damianh** [comment]
@datvm I'm not going accept this proposal as I don't want the library to (accidentally) encourage the developer to perform a dangerous operations. 

If you really need to do this, you can do so by configuring the http client:

```csharp

services.AddProxy(httpClientBuilder =>
{
    httpClientBuilder.ConfigurePrimaryHttpMessageHandler(() => new HttpClientHandler
    {
        ServerCertificateCustomValidationCallback = (_, __, ___, _____) => true
    });
});

```

Note: this is not official guidance. **You are responsible for your code if you ship this to production**.
