### ISSUE TITLE
Fix OptionsPattern for ProxyOptions

### ISSUE THREAD

**Issue by datvm** [damianh/ProxyKit#74]
(I am pushing a pull request soon for this issue)

Currently `Action<ProxyOptions> configureOptions` is never called because of wrong DI declaration:

```
            services.Configure(configureOptions);
            services.AddTransient<ProxyOptions>();
```

Basically, `ProxyOptions` is always created and never configured if we put `configureOptions` in.

Suggestion: change the code to:

```
            services.AddOptions<ProxyOptions>()
                .Configure(configureOptions);
```

And currently, only [`WebSocketProxyMiddleware`](https://github.com/damianh/ProxyKit/blob/master/src/ProxyKit/WebSocketProxyMiddleware.cs) is using it, the correct DI declaration should be:

```
        public WebSocketProxyMiddleware(
            RequestDelegate next,
            IOptionsMonitor<ProxyOptions> options,
            Uri destinationUri,
            ILogger<WebSocketProxyMiddleware> logger)
        {
            _next = next;
            _options = options.CurrentValue;
            _destinationUri = destinationUri;
            _logger = logger;
        }
```

**Comment by damianh** [comment]
Thanks for PR!
