### ISSUE TITLE
Certain requests never return

### ISSUE THREAD

**Issue by madd0** [damianh/ProxyKit#87]
Hi,

I want to replace a legacy app (ASP.NET) with a new one (ASP.NET Core). In order for the change to be transparent for my clients, I installed the new app in place of the old on in IIS and I'm using ProxyKit to selectively redirect the old requests to the old app, while the new one handles new requests. The configuration is as such:

```
app.UseWhen(
    // use proxy if requested path does not start with an item in paths collection
    context => !paths.Any(path => context.Request.Path.StartsWithSegments(path, StringComparison.OrdinalIgnoreCase)),
    appInner => appInner.RunProxy(async context =>
    {
        var response = await context
            .ForwardTo(upstreamHost)
            .CopyXForwardedHeaders()
            .FixContentTypeOnGetRequests(context) // "adjusts" downstream request to support old clients
            .Send();

        // Replace upstream host ONLY in help pages
        if (context.Request.Path.Value.IndexOf("/help", StringComparison.OrdinalIgnoreCase) > -1)
        {
            await ReplaceHostnamesInProxiedResponse(upstreamHost, downstreamHost, response);
        }

        return response;
    }));
```

The configuration works fine most of the time and is fast enough that you can barely tell there is a proxy. Neither `FixContentTypeOnGetRequests` nor the `if` have any incidence on the situation described below.

For some reason I cannot explain, however, some calls to `Send` sometimes never return.

I have only been able to reproduce when calls happen in a very specific sequence:

There are 4 apps hosted in IIS on the same machine: PROXY, DOWNSTREAM, APP1, APP2

```
CLIENT               PROXY             DOWNSTREAM                 APP1                  APP2
   | ---- /path1 ----> |                   |                       |                      |
   |                   | ---- /path1 ----> |                       |                      |
   |                   |                   | ----- /extCall1 ----> |                      |
   |                   |                   |                       | ---- /extCall2 ----> |
   |                   | <-------------------------- /path2 ----------------------------- |
   |                   | ---- /path2 ----> |                       |                      |
   |                   |                   | ----- /extCall3 ----> |                      |
   |                   | <---------------- /path3 ---------------- |                      |
   |                   | ---- /path3 ----> |                       |                      |
   |                   | <--- R /path3 --- |                       |                      |
   |                   |                  TIMEOUT                  |                      |
```

I hope the diagram makes the situation clear. Basically, there is a series of calls which are all synchronous and needed to respond to the initial request. The client requests /path1 to the PROXY, which in turns triggers several other calls to other applications, some of which are further requests to the PROXY.

The third request to the PROXY, /path3, is handled quickly by the DOWNSTREAM app (~100ms), but the call to `Send` in the PROXY that's supposed to get that request and send it to the caller (APP1), never completes, triggering a series of time outs.

Calling making the exact same call directly, works just fine:

```
CLIENT               PROXY             DOWNSTREAM
   | ---- /path3 ----> |                   |
   |                   | ---- /path3 ----> |
   |                   | <--- R /path3 --- |
   | <--- R /path3 --- |                   |
```

Avoiding the PROXY in the last call, also works fine:

```
CLIENT               PROXY             DOWNSTREAM                 APP1                  APP2
   | ---- /path1 ----> |                   |                       |                      |
   |                   | ---- /path1 ----> |                       |                      |
   |                   |                   | ----- /extCall1 ----> |                      |
   |                   |                   |                       | ---- /extCall2 ----> |
   |                   | <-------------------------- /path2 ----------------------------- |
   |                   | ---- /path2 ----> |                       |                      |
   |                   |                   | ----- /extCall3 ----> |                      |
   |                   |                   | <------ /path3 ------ |                      |
   |                   |                   | ------ R /path3 ----> |                      |
   |                   |                   | <--- R /extCall3 ---- |                      |
   |                   | <--- R /path2 --- |                       |                      |
   |                   | -------------------------- R /path2 ---------------------------> |
etc.
```

However, reconfiguring our internal apps to hit DOWNSTREAM directly, totally beats the purpose of setting up the PROXY, so it's something I'd like to avoid.

Is there anything that would explain why this 3rd call to the PROXY simply never returns? It feels like some kind of deadlock, but I cannot figure out why.

Any insights are welcome.

**Comment by madd0** [comment]
I finally tracked down the issue to the `HttpClient` having a limited number of possible simultaneous open connections. This limit was being reached because the `HttpClientFactory` was giving ProxyKit a single `HttpClient` to reuse and, at the same time, each call to the proxy was creating a new connection that remained open because of the triggered sub-calls. Since each sub-call "recursively" called the proxy again, the process restarted.

To support the chained calls I described above, I simply changed the value of `ServicePointManager.DefaultConnectionLimit` from the default of `2` to a higher number in my proxy app's startup class.

**Comment by damianh** [comment]
Firstly sorry I didn't get to this sooner. Been busy last couple of week. Also, excellent report and thank you for getting back.

I think it would have taken me a long time to work out the solution too. 

Side note: there is no ServicePointManager on linux... Hmm..

**Comment by damianh** [comment]
I'm going to keep this open as I think it need documentation or some better way to detect when the issue occurs.
