### ISSUE TITLE
GZip/Deflate Example

### ISSUE THREAD

**Issue by m1dst** [damianh/ProxyKit#99]
Could you please provide a demo of modifying a response which is GZip encoded?

**Comment by m1dst** [comment]
I managed to do something manually.  Is there some kind of automated flags which can be set as with HttpClient?

`using (var msi = response.Content.ReadAsStreamAsync().Result)
{
    using (var mso = new MemoryStream())
    {
        if (response.Content.Headers.ContentEncoding.Contains("gzip"))
        {
            using (var gs = new GZipStream(msi, CompressionMode.Decompress))
            {
                gs.CopyTo(mso);
            }
        }
        // mso at this point is a decompressed stream.

    }
}`

**Comment by damianh** [comment]
That works and is actually more friendly to in-memory integration testing. You can also use [automatic decompression property of HttpClientHandler](https://docs.microsoft.com/en-us/dotnet/api/system.net.http.httpclienthandler.automaticdecompression?view=netframework-4.8) like this:

```csharp
public class Startup1
{
    public void ConfigureServices(IServiceCollection services)
    {
        HttpMessageHandler CreatePrimaryHandler()
        {
            var clientHandler = new HttpClientHandler
            {
                AutomaticDecompression = DecompressionMethods.GZip | DecompressionMethods.Deflate
            };
            return clientHandler;
        }

        services.AddProxy(httpClientBuilder => httpClientBuilder.ConfigurePrimaryHttpMessageHandler(CreatePrimaryHandler));
    }

    public void Configure(IApplicationBuilder app)
    {
        app.RunProxy(context => context
            .ForwardTo("https://host/")
            .AddXForwardedHeaders()
            .Send());
    }
}
```

HTH
